### ISSUE TITLE
Better Descriptions

### ISSUE THREAD

**Issue by SirUmnei** [Zkaface/TAIGA#53] opened 2016-10-26 05:20 UTC
Some of the traits descriptions literally tell you anything. I mean, sure some of them should be like that, but for the vast majority it would be good to know what they actually do. I won't go for something I don't know what it does when I have other materials that I do know what they do. So, could we get some clearer descriptions, please?

**Comment by Zkaface** [comment] 2016-10-26 15:27
yup in 1.2 there will be new and more clearly informations!

**Comment by SPMoo66** [comment] 2016-10-30 03:25
On the note of vague descriptions, can I ask what Solarium's Garishly is supposed to do? From the description, I would think it's some kind of auto-smelt, but what it actually seems to do is destroy blocks around 3/4 of the time. Is this intended...?

**Comment by Zkaface** [comment] 2016-10-30 08:31
@SPMoo66 While block breaking, it has a chance to delete the drop of a block but also has a chance to add up to 6 additional drops from the same state. 

If you like to know more, look at trait garishly in the trait list of the code.

**Comment by SPMoo66** [comment] 2016-11-05 02:41
@Zkaface Are you sure that the 6 additional drops works?

I just ran a test in a superflat world, mining 350 blocks of iron ore, getting 173 single drops and 0 instances of the 6 bonus drops as you claim. I believe that the 1/2 chance works as intended, but I don't think the 6 additional drops actually works.

**Comment by Yowesephth** [comment] 2016-11-25 17:37
I don't know if this is a bit too old to get looked at, but in terms of better descriptions, what is heroic supposed to do? The description and code seems to point to doing more damage when either the player or tool is almost dead, but there doesn't seem to be any damage change, so maybe this isn't the case?

**Comment by Zkaface** [comment] 2016-11-25 17:42
@Yowesephth Look in the code of trait heroic! Atm I start balancing of 1.2 so I have to resources for descriptions of the next outdated version ;-)

**Comment by Zkaface** [comment] 2016-12-24 13:55
Should all be fixed now

**Closed by Zkaface** 2016-12-24 13:55 UTC
Labels: enhancement
