### ISSUE TITLE
killing enderman spawned through Ender IO Powered Spawner (don't know if it works with naturally spawned enderman, assume it does) crashes the server

### ISSUE THREAD

**Issue by maestroke** [Zkaface/TAIGA#88] opened 2016-12-28 14:47 UTC
made a reddit thread on /r/FTBCrashes and they redirected me here, all the info should be in the post: https://www.reddit.com/r/FeedTheBeastCrashes/comments/5kpx6w/server_crash_on_my_own_modpack/?utm_content=title&utm_medium=hot&utm_source=reddit&utm_name=FeedTheBeastCrashes

**Comment by IdleGandalf** [comment] 2016-12-28 19:26
This is a duplicate of #86. Should be fixed with the next release.

**Closed by IdleGandalf** 2016-12-28 19:26 UTC
Labels: duplicate

**Comment by maestroke** [comment] 2016-12-28 19:45
ah, thanks and good luck then
