### ISSUE TITLE
Blocks not breaking correctly most of the times

### ISSUE THREAD

**Issue by vrork** [Zkaface/TAIGA#10] opened 2016-07-20 19:23 UTC
Hello there. after installing your mod, blocks stopped breaking correctly, almost like if there was server lag (in single player), so a lot of the times i have to break the blocks more than once or in case i am using hammers (or any other multi block breaking tool), some blocks dont break, so i have to go and break them.

**Comment by Zkaface** [comment] 2016-07-20 19:25
I need more informations about your environment. Forge version, TiC version, which blocks are being stopped from breaking etc., which kind of material do you use?

**Comment by vrork** [comment] 2016-07-20 19:28
Forge: 12.18.1.2014
TiC: 1.10-2.3.3a
Blocks: Any, mostly noticable (since there is more) stones.
Tool materials: Any material, even vanilla tool this happen.

Also: no config file for us? I cant find any of the higher tier ores (prometheum for example)

**Comment by Zkaface** [comment] 2016-07-20 19:33
The config file will come :) I'm not sure, if it's coming for 1.0.3 oder 1.0.4, but be sure, it's planned to be released. Most things are hardcoded atm. I apologize for it.

The lag sounds weird, because I use the same versions at this moment. Can you exclude, that it's caused by another mod? Of course its a side-effect to one of your other mods?!

**Comment by vrork** [comment] 2016-07-20 19:42
Tried disabling your mod, and it fixed. Its your mod that is causing it. I am not the first one to reporta that tough. If you look at the curse page of your mod, there is another guy saying that. 

Also! Where the hell you find prometheum? Wich levels it spawn?

**Comment by Zkaface** [comment] 2016-07-20 19:51
I just mean a side effect. I can not solve it without knowing the possible mod-combinations with my mod. 

Prometheum: Nether, minY: 48, maxY: 64. Good luck.

**Comment by vrork** [comment] 2016-07-20 19:55
Want me to send a mod list for you? And you have any idea of wich mods can influence on that kind of thing? (i have many mods)

**Comment by Zkaface** [comment] 2016-07-20 19:59
Yes, this wouldn't be bad at all. We gonna check the mod for this issue anyways.

**Comment by vrork** [comment] 2016-07-20 20:17
Here:
http://pastebin.com/bk3JAcbd

**Comment by Zkaface** [comment] 2016-07-21 15:10
In 1.0.3 it should be fixed!

**Closed by Zkaface** 2016-07-21 15:10 UTC
Labels: bug

**Comment by vrork** [comment] 2016-07-21 15:17
Alright. Waiting for the update then. (ETA for it?)

**Comment by Zkaface** [comment] 2016-07-21 15:18
~ Half an hour.
