### ISSUE TITLE
Crash with New Tinkers Construct TConstruct-1.10.2-2.5.2

### ISSUE THREAD

**Issue by tacogerbil** [Zkaface/TAIGA#45] opened 2016-09-23 16:02 UTC
Thanks for your hard work on this mod ;)  So far so good 🎯 ,

I didn't realize there was an ALPHA that works with Tinker's... Sorry!... The Alpha works AS YA'LL stated it does with the new Tinkers ;)  Sorry for the hassle... I don't usually look at the Alphas... was a bit desperate for a solution!!  :)

[08:56:17] [Server thread/INFO]: Starting minecraft server version 1.10.2
[08:57:08] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchFieldError: enderference

	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:610) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoSuchFieldError: enderference
	at com.sosnitzka.taiga.MaterialTraits.<clinit>(MaterialTraits.java:55) ~[MaterialTraits.class:?]
	at com.sosnitzka.taiga.TAIGA.registerTinkerMaterials(TAIGA.java:140) ~[TAIGA.class:?]
	at com.sosnitzka.taiga.TAIGA.preInit(TAIGA.java:57) ~[TAIGA.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595) ~[forge-1.10.2-12.18.1.2090-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:53) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:607) ~[Loader.class:?]
	... 5 more
[08:57:08] [Server thread/ERROR]: This crash report has been saved to: /Users/adam/Desktop/MC/110/BungeeCord/SpongeForge/./crash-reports/crash-2016-09-23_08.57.08-server.txt
[08:57:08] [Server thread/INFO]: Stopping server
[08:57:08] [Server thread/INFO]: Saving worlds

**Comment by garath77** [comment] 2016-09-24 01:09
I'm having what appears to be the same issue:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.55-beta.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 9/23/16 8:04 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchFieldError: enderference
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:612)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldError: enderference
	at com.sosnitzka.taiga.MaterialTraits.<clinit>(MaterialTraits.java:55)
	at com.sosnitzka.taiga.TAIGA.registerTinkerMaterials(TAIGA.java:140)
	at com.sosnitzka.taiga.TAIGA.preInit(TAIGA.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:609)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1501372552 bytes (1431 MB) / 2095579136 bytes (1998 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2092 38 mods loaded, 38 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2092.jar) 
	UCH	Forge{12.18.1.2092} [Minecraft Forge] (forge-1.10.2-12.18.1.2092.jar) 
	UCH	actuallyadditions{1.10.2-r63} [Actually Additions] (ActuallyAdditions-1.10.2-r63.jar) 
	UCH	basemetals{2.4.0} [Base Metals] (BaseMetals_1.10.2-2.4.0.11.jar) 
	UCH	BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar) 
	UCH	JEI{3.10.0.261} [Just Enough Items] (jei_1.10.2-3.10.0.261.jar) 
	UCH	blockdrops{1.0.11} [Block Drops] (BlockDrops-1.10.2-1.0.11.jar) 
	UCH	bookshelfapi{3.3.0} [Bookshelf] (Bookshelf-API-1.10.2-3.3.0.jar) 
	UCH	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCH	chiselsandbits{12.1} [Chisels & Bits] (chiselsandbits-12.1.jar) 
	UCH	StorageDrawers{1.10.2-3.2.7} [Storage Drawers] (StorageDrawers-1.10.2-3.2.7.jar) 
	UCH	bitdrawers{0.31} [Drawers & Bits] (DrawersBits-1.10.2-0.31.jar) 
	UCH	endercore{1.10.2-0.4.1.55-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.55-beta.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCH	EnderIO{1.10.2-3.0.1.112_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.112_beta.jar) 
	UCH	FFS{1.9.4-1.6.4-b28} [Fancy Fluid Storage] (Fancy Fluid Storage-1.9.4-1.6.4-b28.jar) 
	UCH	glass_shards{1.6.2} [Glass Shards] (glass_shards_mc1.9.4-1.6.2.jar) 
	UCH	hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.jar) 
	UCH	ice_shards{1.4.2} [Ice Shards] (ice_shards_mc1.9.4-1.4.2.jar) 
	UCH	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCH	japta{1.9.1} [JAPTA] (JAPTA-1.9.4-1.9.1.jar) 
	UCH	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCH	jeresources{0.5.1.56} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.1.56.jar) 
	UCH	lit{@VERSION@} [Little Insignificant Things] (LittleInsignificantThings-1.10-3.0.3.jar) 
	UCH	lozmod{4.0.0-pre3} [Legend of Zelda Mod V4] (lozmod-4.0-pre3.jar) 
	UCH	mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
	UCH	tconstruct{1.10.2-2.5.2.jenkins352} [Tinkers' Construct] (TConstruct-1.10.2-2.5.2.jar) 
	UCH	neotech{3.3.0} [NeoTech] (NeoTech-1.10.2-3.3.0.jar) 
	UCH	orespawn{1.1.0} [Ore Spawn] (OreSpawn_1.10.2-1.1.0.jar) 
	UCH	RTG{1.10.2} [Realistic Terrain Generation] (RTG-1.10.2-4.1.1.2-snapshot-7.jar) 
	UCH	simpleoregen{1.10.2-0.4.3} [SimpleOreGen] (simpleoregen-1.10.2-0.4.3.jar) 
	UCE	taiga{${version}} [Tinkers Alloying Addon] (taiga-1.10.2-1.1.2.jar) 
	UCH	tinker_io{release 2.3.6} [Tinker I/O] (tinker_io-1.10.2-release 2.3.6.jar) 
	UCH	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UCH	WailaHarvestability{1.1.8} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.8.jar) 
	UCH	WIT{1.0.20} [WIT] (WIT-1.9.4-1.0.20-38.jar) 
	UCH	Woot{1.10.2-1.1.0} [Woot] (woot-1.10.2-1.1.0.jar) 
	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.55-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4229' Renderer: 'Intel(R) HD Graphics 3000'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Chris/Documents/Curse/Minecraft/Instances/Tinkers%20Construct%20+/mods/ActuallyAdditions-1.10.2-r63.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Chris/Documents/Curse/Minecraft/Instances/Tinkers%20Construct%20+/mods/ActuallyAdditions-1.10.2-r63.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Chris/Documents/Curse/Minecraft/Instances/Tinkers%20Construct%20+/mods/ActuallyAdditions-1.10.2-r63.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Chris/Documents/Curse/Minecraft/Instances/Tinkers%20Construct%20+/mods/ActuallyAdditions-1.10.2-r63.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Chris/Documents/Curse/Minecraft/Instances/Tinkers%20Construct%20+/mods/ActuallyAdditions-1.10.2-r63.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Chris/Documents/Curse/Minecraft/Instances/Tinkers%20Construct%20+/mods/ActuallyAdditions-1.10.2-r63.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Chris/Documents/Curse/Minecraft/Instances/Tinkers%20Construct%20+/mods/ActuallyAdditions-1.10.2-r63.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Chris/Documents/Curse/Minecraft/Instances/Tinkers%20Construct%20+/mods/ActuallyAdditions-1.10.2-r63.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Chris/Documents/Curse/Minecraft/Instances/Tinkers%20Construct%20+/mods/Bookshelf-API-1.10.2-3.3.0.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Chris/Documents/Curse/Minecraft/Instances/Tinkers%20Construct%20+/mods/Bookshelf-API-1.10.2-3.3.0.jar!/cofh/api/energy/TileEnergyHandler.class

**Comment by Zkaface** [comment] 2016-09-24 08:00
Wtf, could you please put this damn crash report in a separate file? Please use hastebin or pastebin and write down the link. 

For the crash I will try to find some time. Maybe I'm finished with my job related stuff on Tuesday!

**Comment by IdleGandalf** [comment] 2016-09-24 13:10
No need to look into it, it's already fixed in the latest alpha. I'm closing this now.

**Closed by IdleGandalf** 2016-09-24 13:10 UTC
